### ISSUE TITLE
Create Navbar 

### ISSUE THREAD

**Issue by ashleighctucker** [ashleighctucker/OpenTableClone#16]
## Navbar Notes
  * Logo on left 
  * Search in middle **_(search functionality is in another GH issue!)_**
  * If logged out, log in and sign up buttons on the right
  * If logged in, display first name and link to profile page (maybe like to favorites with a little star icon), log out button

**Comment by CamTangalakis** [comment]
Nav bar is created and has a little bit of style. Menu / profile buttons and places for logo and search to go
