### ISSUE TITLE
Add demo user login buttons to the existing login and signup forms 

### ISSUE THREAD

**Issue by ashleighctucker** [ashleighctucker/OpenTableClone#4]
### Add a button/func that will log in to the demo user in our db. 

- Add a demo button to the login form on front end
- Add a demo button to the signup form on front end
- Create a func to log in the demo user 

## User Story: Demo User
* As an unregistered and unauthorized user, I would like an easy to find and clear button on both the signup` and login modals to allow me to visit the site as a guest without signing up or logging in.
* When I'm on either the signup or login modals: 
  * I can click on a Demo User button to log me in and allow me access as a normal user.

**Comment by CamTangalakis** [comment]
demo user buttons added on 'navbar' branch
